name: 📦️ Publish container image
on:
  workflow_call:
    inputs:
      image-tag:
        default: latest
        type: string

jobs:
  build-and-publish:
    name: Build docker image and publish to GitHub Container Registry.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate against GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin

      - name: Build container image
        run: IMAGE_TAG=${{ inputs.image-tag }} docker compose build

      - name: Publish Container Image
        run: IMAGE_TAG=${{ inputs.image-tag }} docker compose push
